### ISSUE TITLE
Can fastapi-async-sqlalchemy work outside the HTTP request context?

### ISSUE THREAD

**Issue by longma8520** [h0rn3t/fastapi-async-sqlalchemy#14]
Can fastapi-async-sqlalchemy work outside the HTTP request context?
e.g.: In a celery shared_task
Thanks

**Comment by h0rn3t** [comment]
Yes but you must use some thing like that https://github.com/the-wondersmith/celery-aio-pool
using it myself on production

**Comment by h0rn3t** [comment]
if you want i can show examples

**Comment by nlyn** [comment]
> if you want i can show examples

I would be interested in this

**Comment by h0rn3t** [comment]
`import time
from datetime import datetime

import sqlalchemy as sa
import taskiq_fastapi
from fastapi import FastAPI
from fastapi_async_sqlalchemy import SQLAlchemyMiddleware, db
from taskiq import TaskiqEvents, TaskiqScheduler, TaskiqState
from taskiq.schedule_sources import LabelScheduleSource
from taskiq.serializers import ORJSONSerializer
from taskiq_aio_pika import AioPikaBroker
from taskiq_elastic_apm import ElasticApmMiddleware

from datahub_core.datetime_utils import localize_datetime

from app.core.constants import Z_COUNT_CACHE_KEY
from app.core.models import Locking
from app.core.redis import client as redis_client
from app.core.settings import apm, settings

broker = AioPikaBroker(
    url=settings.CELERY_BROKER_URL,
    queue_name=settings.CELERY_DEFAULT_QUEUE,
    exchange_name=settings.CELERY_DEFAULT_QUEUE,
).with_middlewares(
    ElasticApmMiddleware(
        client=apm,
    )
)

broker.serializer = ORJSONSerializer()
scheduler = TaskiqScheduler(
    broker=broker,
    sources=[LabelScheduleSource(broker)],
)
taskiq_fastapi.init(broker, "app.main:app")


@broker.on_event(TaskiqEvents.WORKER_STARTUP)
async def startup(state: TaskiqState) -> None:
    SQLAlchemyMiddleware(
        FastAPI(),  # fake app
        db_url=settings.DATABASE_URL,
        engine_args={
            "echo": settings.SQLALCHEMY_ECHO,
            "pool_pre_ping": True,
            "pool_size": settings.DB_POOL_SIZE_MIN,
            "max_overflow": settings.DB_POOL_SIZE_MAX,
            "connect_args": {
                "server_settings": {"jit": "off"},
                # "prepared_statement_cache_size": 0,
                "statement_cache_size": 0,
            },
        },
    )


@broker.task(schedule=[{"cron": "0 0 * * *"}])
async def lock_again():
    async with db(commit_on_exit=True):
        locks = await db.session.execute(
            sa.select(Locking).where(
                Locking.ttl <= localize_datetime(datetime.utcnow()),
            )
        )
        for lock in locks.scalars().all():
            await db.session.delete(lock)`
