### ISSUE TITLE
missed test coverage for the lines after calling db.session

### ISSUE THREAD

**Issue by pangan** [h0rn3t/fastapi-async-sqlalchemy#3]
If calling a `await db.session.X` in a method, then all lines after that will be missed test coverage (pytest-cov) but adding a `await asyncio.sleep(0)` after that, fixes the issue.
seems it is a but in fastapi-async-sqlalchemy

example to reproduce:

```
@v1_router.post("/")
async def foo():
    await db.session.execute("show databases")
    a = 1
    return {"status": "OK"}
```
This shows missed coverage at the below lines:
```
  a = 1
  return {"status": "OK"}
```

but this one is ok:

```
@v1_router.post("/")
async def foo():
    await db.session.execute("show databases")
    await asyncio.sleep(0)
    a = 1
    return {"status": "OK"}
```

**Comment by owjs3901** [comment]
@h0rn3t How to fix it? Our team is experiencing the same problem.

**Comment by owjs3901** [comment]
I fixed issue.

Add `concurrency = ["greenlet"]` to `pyproject.toml` or `.coveragerc`!

![image](https://github.com/h0rn3t/fastapi-async-sqlalchemy/assets/12480623/341e3754-f532-47c4-969f-9ec0d402d997)
![image](https://github.com/h0rn3t/fastapi-async-sqlalchemy/assets/12480623/3aaa0c9c-4c93-427b-afbc-791ad7ce6d85)
