### ISSUE TITLE
Multiple DBs

### ISSUE THREAD

**Issue by karserasl** [h0rn3t/fastapi-async-sqlalchemy#7]
Hello

With this method, is it possible to connect to multiple dbs?

Thanks

**Comment by EwenLo** [comment]
If you need multiple DB support checkout https://github.com/Ewen-Zippedscript/fastapi-sqlalchemy

**Comment by h0rn3t** [comment]
> If you need multiple DB support checkout https://github.com/Ewen-Zippedscript/fastapi-sqlalchemy

that lib not async
