### ISSUE TITLE
TypeError: connect() got an unexpected keyword argument 'statement_cache_size'

### ISSUE THREAD

**Issue by harunurkst** [h0rn3t/fastapi-async-sqlalchemy#9]
I am using sqlalchemy 2.0 and getting these two error

`TypeError: connect() got an unexpected keyword argument 'statement_cache_size'`  
`TypeError: connect() got an unexpected keyword argument 'prepared_statement_cache_size'`

If I remove keys from connect_args, then the error is solved. What should be proper arguments?

**Comment by h0rn3t** [comment]
this need for fix PGBOUNCER, https://github.com/PrefectHQ/prefect/issues/6014
